[2021-09-05 21:06:27,928] INFO [GroupCoordinator 1]: Member consumer-third_app-1-5610e945-ae1d-42c1-bcb8-5dd56405be34 in group third_app has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:06:27,929] INFO [GroupCoordinator 1]: Preparing to rebalance group third_app in state PreparingRebalance with old generation 5 (__consumer_offsets-39) (reason: removing member consumer-third_app-1-5610e945-ae1d-42c1-bcb8-5dd56405be34 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:06:27,929] INFO [GroupCoordinator 1]: Group third_app with generation 6 is now empty (__consumer_offsets-39) (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:22:34,895] INFO [GroupCoordinator 1]: Preparing to rebalance group test-group in state PreparingRebalance with old generation 0 (__consumer_offsets-12) (reason: Adding new member consumer-test-group-1-4ba1877c-9add-464f-83cd-2a19cf6f6ad8 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:22:34,895] INFO [GroupCoordinator 1]: Stabilized group test-group generation 1 (__consumer_offsets-12) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:22:34,900] INFO [GroupCoordinator 1]: Assignment received from leader for group test-group for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:29:29,977] INFO [GroupCoordinator 1]: Member consumer-test-group-1-4ba1877c-9add-464f-83cd-2a19cf6f6ad8 in group test-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:29:29,978] INFO [GroupCoordinator 1]: Preparing to rebalance group test-group in state PreparingRebalance with old generation 1 (__consumer_offsets-12) (reason: removing member consumer-test-group-1-4ba1877c-9add-464f-83cd-2a19cf6f6ad8 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:29:29,978] INFO [GroupCoordinator 1]: Group test-group with generation 2 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2021-09-05 21:32:52,326] WARN [SocketServer listenerType=ZK_BROKER, nodeId=1] Unexpected error from /0:0:0:0:0:0:0:1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-09-05 21:32:53,356] WARN [SocketServer listenerType=ZK_BROKER, nodeId=1] Unexpected error from /0:0:0:0:0:0:0:1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2021-09-05 21:32:58,375] WARN [SocketServer listenerType=ZK_BROKER, nodeId=1] Unexpected error from /0:0:0:0:0:0:0:1; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
